version: "3"
services:
  front-end-app:
    build: ./Frontend
    container_name: Frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    command: npm run dev
  payment_service:
    build: ./Backend/Payment_service
    container_name: Payment_service
    ports:
      - "4000:4000"
    volumes:
      - ./Backend/Payment_service:/app
      - /app/node_modules
    env_file:
      - ./Backend/Payment_service/.env
    environment:
      - NODE_ENV=development
    command: npm run dev
  product_service:
    build: ./Backend/Product_service
    container_name: Product_service
    ports:
      - "4001:4001"
    volumes:
      - ./Backend/Product_service:/app
      - /app/node_modules
    env_file:
      - ./Backend/Product_service/.env
    environment:
      - NODE_ENV=development
    command: npm run dev
  user_service:
    build: ./Backend/User_service
    container_name: User_service
    ports:
      - "4002:4002"
    volumes:
      - ./Backend/User_service:/app
      - /app/node_modules
    env_file:
      - ./Backend/User_service/.env
    environment:
      - NODE_ENV=development
    command: npm run dev
