version: "3"
services:
  front-end-app:
    build: ./Frontend
    container_name: Frontend
    ports: 
      - "3000:3000"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    command: npm run serve
  payment_service:
    build: ./Backend/Payment_service
    container_name: Payment_service
    ports: 
      - "4000:4000"
    volumes:
      - ./Backend/Payment_service:/app
      - /app/node_modules
    env_file:
      - ./Backend/Payment_service/.env
    environment:
      - NODE_ENV=production
    command: npm run start
  product_service:
    build: ./Backend/product_service
    container_name: Product_service
    ports: 
      - "4001:4001"
    volumes:
      - ./Backend/product_service:/app
      - /app/node_modules
    env_file:
      - ./Backend/product_service/.env
    environment:
      - NODE_ENV=production
    command: npm run start
  user_service:
    build: ./Backend/user_service
    container_name: User_service
    ports: 
      - "4002:4002"
    volumes:
      - ./Backend/user_service:/app
      - /app/node_modules
    env_file:
      - ./Backend/user_service/.env
    environment:
      - NODE_ENV=production
    command: npm run start